name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.16.0
      - name: Build docs
        run: zig build docs
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/docs
      - id: deployment
        uses: actions/deploy-pages@v4
